# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run setup
      - run: npm run build

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --headless --disable-gpu --print-to-pdf=build/resume-ugo-quelhas.en_en.pdf --no-margins build/resume.en_en.html
      - run: chrome --headless --disable-gpu --print-to-pdf=build/resume-ugo-quelhas.fr_fr.pdf --no-margins build/resume.fr_fr.html

      - uses: actions/upload-artifact@v2
        with:
          name: resume-ugo-quelhas
          path: build/resume?.pdf
